---
include:
  - board: nice_nano_v2
    shield: skeletyl_34_left
  - board: nice_nano_v2
    shield: skeletyl_34_right

  - board: nice_nano_v2
    shield: skeletyl_left
  - board: nice_nano_v2
    shield: skeletyl_right

  - board: nice_nano_v2
    shield: dilemma_left
  - board: nice_nano_v2
    shield: dilemma_right

  - board: nice_nano_v2
    shield: settings_reset
