manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 1dccb7fe50a349cda94603042b5e81ae7c606c2a
      import: app/west.yml
  self:
    path: config
