manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zmkfirmware
    - name: 0xcharly
      url-base: https://github.com/0xcharly

  projects:
    - name: zmk-keyboards-delay
      remote: 0xcharly
      revision: main
      path: modules/zmk-keyboards-delay

    - name: zmk
      remote: upstream
      revision: main
      import: app/west.yml

  self:
    path: config
