manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: xudongzheng
      url-base: https://github.com/xudongzheng

  projects:
    - name: zmk-auto-layer
      remote: urob
      revision: main
      path: modules/auto-layer

    # ZMK with Zephyr namespaced under /zmk. This requires that ZMK imports
    # Zephyr with a path other than `zephyr` (as in `going-modular`).
    - name: zmk
      remote: xudongzheng
      revision: split-serial-pr
      import: app/west.yml
      # path: .
      # import:
      #   file: app/west.yml
      #   path-prefix: zmk

  self:
    path: config
