identifier: rp2040_ce
name: RP2040 Community Edition
type: mcu
arch: arm
flash: 8192
ram: 264
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - uart
  - gpio
  - adc
  - i2c
  - spi
  - hwinfo
  - watchdog
  - pwm
  - flash
  - dma
