file_format: "1"
id: skeletyl
name: Skeletyl
type: shield
url: https://github.com/0xcharly/zmk-keyboards-delay
requires:
  - pro_micro
exposes:
features:
  - keys
siblings:
  - skeletyl_left
  - skeletyl_right
